# -*- coding: utf-8 -*-
"""DOM_Banking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlxShAj4u_N5sKXfPEtB4_i1D0FwYfoF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import joblib  # To save the model for deployment

df = pd.read_excel('/content/Bank_Personal_Loan_Modelling.xlsx')
df.head()

print(df.isnull().sum())

print(f"Duplicate rows: {df.duplicated().sum()}")

plt.figure(figsize=(12,6))
sns.boxplot(data=df[['Age', 'Experience', 'Income', 'CCAvg', 'Mortgage']])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# List of continuous columns to visualize
cols_to_plot = ['Age', 'Experience', 'Income', 'CCAvg', 'Mortgage']

# --- 1. Plot BEFORE Treatment ---
plt.figure(figsize=(18, 5))
for i, col in enumerate(cols_to_plot, 1):
    plt.subplot(1, 5, i)
    sns.boxplot(y=df[col], color='skyblue')
    plt.title(f'Before: {col}')
plt.tight_layout()
plt.show()

# --- 2. Apply Domain-Specific Treatment ---

# A. Fix Negative Experience (Data Entry Error)
df['Experience'] = df['Experience'].abs()

# B. IQR Capping Function (Winsorization)
def cap_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    upper_limit = Q3 + 1.5 * IQR
    lower_limit = Q1 - 1.5 * IQR

    # Capping values
    df[column] = np.where(df[column] > upper_limit, upper_limit,
                 np.where(df[column] < lower_limit, lower_limit, df[column]))
    return df

# Apply capping ONLY to Income and CCAvg [Domain Expertise]
for col in ['Income', 'CCAvg']:
    df = cap_outliers(df, col)

# --- 3. Plot AFTER Treatment ---
plt.figure(figsize=(18, 5))
for i, col in enumerate(cols_to_plot, 1):
    plt.subplot(1, 5, i)
    sns.boxplot(y=df[col], color='lightgreen')
    plt.title(f'After: {col}')
plt.tight_layout()
plt.show()

# Drop non-predictive columns
df.drop(['ID', 'ZIP Code'], axis=1, inplace=True)

# Check the final shape
print(f"Final dataset shape: {df.shape}")
df.head()

df.hist(figsize=(15, 10), bins=20)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Features')
plt.show()

x = df.drop('Personal Loan', axis=1)
y = df['Personal Loan']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
import joblib

scaler = StandardScaler()

# Scaling continuous intervals: Age, Experience, Income, CCAvg, Mortgage
cols_to_scale = ['Age', 'Experience', 'Income', 'CCAvg', 'Mortgage']

x_train_scaled = x_train.copy()
x_test_scaled = x_test.copy()

x_train_scaled[cols_to_scale] = scaler.fit_transform(x_train[cols_to_scale])
x_test_scaled[cols_to_scale] = scaler.transform(x_test[cols_to_scale])

# SAVE THE SCALER - Essential for Part B, C, and D [cite: 13, 24, 25, 27]
joblib.dump(scaler, 'scaler.pkl')

plt.figure(figsize=(6, 4))
sns.countplot(x=y)
plt.title('Distribution of Personal Loan (Target Variable)')
plt.xlabel('Personal Loan')
plt.ylabel('Count')
plt.show()

from imblearn.over_sampling import SMOTE

# 1. Initialize SMOTE with a fixed random state for reproducibility
smote = SMOTE(random_state=42)

# 2. Apply SMOTE to the Scaled Training Data
# This addresses class imbalance in the training set [cite: 18]
x_train_res, y_train_res = smote.fit_resample(x_train_scaled, y_train)

# 3. Apply SMOTE to the Scaled Testing Data
# Note: This balances the classes (0s and 1s) in the test set per instructor requirement
x_test_res, y_test_res = smote.fit_resample(x_test_scaled, y_test)

# 4. Verification of the new distributions
print("--- Resampling Results ---")
print(f"Training Set - Original 1s: {y_train.sum()}, Resampled 1s: {y_train_res.sum()}")
print(f"Testing Set  - Original 1s: {y_test.sum()}, Resampled 1s: {y_test_res.sum()}")
print(f"\nFinal Training Shape: {x_train_res.shape}")
print(f"Final Testing Shape: {x_test_res.shape}")

import statsmodels.api as sm

# Adding constant to the resampled and scaled training data
x_train_res_sm = sm.add_constant(x_train_res)

# Initialize and fit the Logistic Regression model using Statsmodels [cite: 13]
sm_log_reg_model = sm.Logit(y_train_res, x_train_res_sm)
sm_log_reg_result = sm_log_reg_model.fit()

# Print the summary to see the new P-values and Coefficients
print(sm_log_reg_result.summary())

import statsmodels.api as sm
import pandas as pd

def perform_dynamic_backward_elimination(X, y, significance_level=0.05):
    # Start with all features in x_train_res
    features = X.columns.tolist()
    iteration = 1

    while len(features) > 0:
        # Step 1: Add constant and fit the model dynamically
        X_with_const = sm.add_constant(X[features])
        model = sm.Logit(y, X_with_const).fit(disp=0)

        # Step 2: Access p-values dynamically (excluding the constant)
        p_values = model.pvalues.drop('const')
        max_p_value = p_values.max()
        max_p_feature = p_values.idxmax()

        # Step 3: Verify and drop if above significance level
        if max_p_value > significance_level:
            print(f"Iteration {iteration}: Dropping '{max_p_feature}' (p-value: {max_p_value:.4f})")
            features.remove(max_p_feature)
            iteration += 1
        else:
            print(f"Final Model reached. All {len(features)} features are significant (p < {significance_level}).")
            break

    return model, features

# Execute the dynamic process
final_sm_model, final_features = perform_dynamic_backward_elimination(x_train_res, y_train_res)

# Print the final result summary for your report
print(final_sm_model.summary())

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

# 1. Use the dynamically selected features from your loop
# 'final_features' was defined in the previous dynamic loop step
print(f"Final Features used for verification: {final_features}")

# 2. Add constant to the RESAMPLED test set to match model structure
# We use x_test_res because SMOTE was applied to the test data as well
x_test_res_sm = sm.add_constant(x_test_res[final_features])

# 3. Generate Predictions using the resampled test data
# 'final_sm_model' is the result of your dynamic backward elimination
y_prob = final_sm_model.predict(x_test_res_sm)
y_pred = (y_prob > 0.5).astype(int)

# --- 4. CLASSIFICATION REPORT & ACCURACY ---
# Using y_test_res for a consistent comparison against balanced data
print("--- Classification Report (Balanced Test Set) ---")
print(classification_report(y_test_res, y_pred))
print(f"Final Model Accuracy: {accuracy_score(y_test_res, y_pred):.4f}")

# --- 5. CONFUSION MATRIX ---
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test_res, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', cbar=False)
plt.title('Confusion Matrix: Optimized Loan Model')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# --- 6. ROC-AUC CURVE ---
fpr, tpr, thresholds = roc_curve(y_test_res, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc="lower right")
plt.show()

import joblib

# Save the model, the scaler, and the final feature list for deployment
# These are required for Flask, Streamlit, and FastAPI (Parts B, C, D)
joblib.dump(final_sm_model, 'loan_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(final_features, 'final_features.pkl')

print("All artifacts saved successfully. Ready for Part B: Flask Deployment.")

